export const SECTIONS = [
  {
    id: 'appearance',
    label: 'Appearance',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2m-3.64-6.36-1.42 1.42M6.06 17.94l-1.42 1.42m0-12.72 1.42 1.42M17.94 17.94l1.42 1.42"/></svg>`,
    group: 'APPEARANCE',
    subsections: [
      {
        id: 'general',
        label: 'General',
        sectionPath: ['general'],
        settings: [
          { key: 'gaps_in', label: 'Inner Gaps', type: 'range', min: 0, max: 60, step: 1, unit: 'px', desc: 'Gap between windows' },
          { key: 'gaps_out', label: 'Outer Gaps', type: 'range', min: 0, max: 120, step: 1, unit: 'px', desc: 'Gap between windows and monitor edges' },
          { key: 'float_gaps', label: 'Floating Gaps', type: 'range', min: -1, max: 120, step: 1, unit: 'px', desc: 'Gaps for floating windows' },
          { key: 'gaps_workspaces', label: 'Workspace Gaps', type: 'range', min: 0, max: 120, step: 1, unit: 'px', desc: 'Extra gap between workspace edges' },
          { key: 'border_size', label: 'Border Size', type: 'range', min: 0, max: 20, step: 1, unit: 'px', desc: 'Window border thickness' },
          { key: 'col.active_border', label: 'Active Border Color', type: 'color', desc: 'Color/gradient of the focused window border' },
          { key: 'col.inactive_border', label: 'Inactive Border Color', type: 'color', desc: 'Color/gradient of unfocused window borders' },
          { key: 'col.nogroup_border', label: 'No-Group Border', type: 'color', desc: 'Border color for windows that cannot be grouped' },
          { key: 'col.nogroup_border_active', label: 'No-Group Active Border', type: 'color', desc: 'Active border color for non-groupable windows' },
          { key: 'no_focus_fallback', label: 'No Focus Fallback', type: 'bool', desc: 'Disable focus fallback when no target can be found' },
          { key: 'resize_on_border', label: 'Resize on Border', type: 'bool', desc: 'Allow resizing by dragging border/gap area' },
          { key: 'extend_border_grab_area', label: 'Border Grab Area', type: 'range', min: 0, max: 60, step: 1, unit: 'px', desc: 'Extra resize-grab area around borders' },
          { key: 'hover_icon_on_border', label: 'Hover Icon on Border', type: 'bool', desc: 'Show resize cursor when hovering border' },
          { key: 'allow_tearing', label: 'Allow Tearing', type: 'bool', desc: 'Master switch for tearing support' },
          { key: 'resize_corner', label: 'Resize Corner', type: 'range', min: 0, max: 4, step: 1, unit: '', desc: 'Corner used for floating resize handle, 0 disables' },
          { key: 'snap', label: 'Snap Distance', type: 'range', min: 0, max: 50, step: 1, unit: 'px', desc: 'Floating snap distance threshold' },
          { key: 'snap', label: 'Snap Distance', type: 'range', min: 0, max: 50, step: 1, unit: 'px', desc: 'Floating snap distance threshold' },
          { key: 'layout', label: 'Default Layout', type: 'select', options: ['dwindle', 'master', 'scrolling', 'monocle'], desc: 'Default tiling layout' },
        ],
      },
      {
        id: 'general_snap',
        label: 'Snap',
        sectionPath: ['general'],
        settings: [
          { key: 'snap', label: 'Snap Distance', type: 'range', min: 0, max: 50, step: 1, unit: 'px', desc: 'Distance for floating snap behavior' },
        ],
      },
      {
        id: 'decoration',
        label: 'Decoration',
        sectionPath: ['decoration'],
        settings: [
          { key: 'rounding', label: 'Corner Rounding', type: 'range', min: 0, max: 40, step: 1, unit: 'px', desc: 'Rounded corner radius for windows' },
          { key: 'rounding_power', label: 'Rounding Power', type: 'range', min: 1, max: 10, step: 0.1, unit: '', desc: 'Curve power for rounding shape' },
          { key: 'active_opacity', label: 'Active Opacity', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Opacity of the focused window' },
          { key: 'inactive_opacity', label: 'Inactive Opacity', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Opacity of unfocused windows' },
          { key: 'fullscreen_opacity', label: 'Fullscreen Opacity', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Opacity of fullscreen windows' },
          { key: 'dim_inactive', label: 'Dim Inactive', type: 'bool', desc: 'Dim unfocused windows' },
          { key: 'dim_strength', label: 'Dim Strength', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Strength of inactive dimming' },
          { key: 'dim_special', label: 'Dim Special', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Dim amount behind the special workspace' },
          { key: 'dim_around', label: 'Dim Around', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Dim amount used by dim_around rules' },
          { key: 'dim_modal', label: 'Dim Modal', type: 'bool', desc: 'Dim parent windows of modals' },
          { key: 'screen_shader', label: 'Screen Shader', type: 'text', desc: 'Path to a GLSL screen shader file' },
          { key: 'border_part_of_window', label: 'Border Part of Window', type: 'bool', desc: 'Treat borders as part of window geometry' },
        ],
      },
      {
        id: 'blur',
        label: 'Blur',
        sectionPath: ['decoration', 'blur'],
        settings: [
          { key: 'enabled', label: 'Enable Blur', type: 'bool', desc: 'Enable background blur' },
          { key: 'size', label: 'Blur Size', type: 'range', min: 1, max: 20, step: 1, unit: 'px', desc: 'Blur kernel size' },
          { key: 'passes', label: 'Blur Passes', type: 'range', min: 1, max: 10, step: 1, unit: '', desc: 'Number of blur passes' },
          { key: 'vibrancy', label: 'Vibrancy', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Boost vibrancy of blurred colors' },
          { key: 'vibrancy_darkness', label: 'Vibrancy Darkness', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'How much vibrancy affects dark colors' },
          { key: 'noise', label: 'Noise', type: 'range', min: 0, max: 1, step: 0.0001, unit: '', desc: 'Dither noise applied to blur' },
          { key: 'contrast', label: 'Contrast', type: 'range', min: 0, max: 2, step: 0.01, unit: '', desc: 'Blur layer contrast' },
          { key: 'brightness', label: 'Brightness', type: 'range', min: 0, max: 2, step: 0.01, unit: '', desc: 'Blur layer brightness' },
          { key: 'xray', label: 'X-Ray Mode', type: 'bool', desc: 'Make floating blur ignore tiled windows' },
          { key: 'ignore_opacity', label: 'Ignore Opacity', type: 'bool', desc: 'Make blur work even on opaque windows' },
          { key: 'new_optimizations', label: 'Optimizations', type: 'bool', desc: 'Enable new blur optimizations' },
          { key: 'special', label: 'Blur Special', type: 'bool', desc: 'Enable blur on special workspace' },
          { key: 'popups', label: 'Blur Popups', type: 'bool', desc: 'Enable blur on popup windows' },
          { key: 'popups_ignorealpha', label: 'Popups Ignore Alpha', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Skip blurring popup pixels below this alpha' },
          { key: 'input_methods', label: 'Blur Input Methods', type: 'bool', desc: 'Enable blur on input methods like fcitx5' },
          { key: 'input_methods_ignorealpha', label: 'IME Ignore Alpha', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Skip IME blur below this alpha' },
        ],
      },
      {
        id: 'shadow',
        label: 'Shadow',
        sectionPath: ['decoration', 'shadow'],
        settings: [
          { key: 'enabled', label: 'Enable Shadow', type: 'bool', desc: 'Enable drop shadows on windows' },
          { key: 'range', label: 'Shadow Range', type: 'range', min: 0, max: 100, step: 1, unit: 'px', desc: 'Shadow rendering distance' },
          { key: 'render_power', label: 'Render Power', type: 'range', min: 1, max: 4, step: 1, unit: '', desc: 'Shadow falloff sharpness' },
          { key: 'sharp', label: 'Sharp Shadow', type: 'bool', desc: 'Render sharp shadows' },
          { key: 'ignore_window', label: 'Ignore Window Body', type: 'bool', desc: 'Render shadow only around the outer contour' },
          { key: 'color', label: 'Shadow Color', type: 'color', desc: 'Shadow color' },
          { key: 'color_inactive', label: 'Inactive Shadow Color', type: 'color', desc: 'Shadow color for inactive windows' },
          { key: 'offset', label: 'Shadow Offset', type: 'text', desc: 'Shadow offset as "X Y"' },
          { key: 'scale', label: 'Shadow Scale', type: 'range', min: 0, max: 1.5, step: 0.01, unit: '', desc: 'Scale of shadow' },
        ],
      },
      {
        id: 'glow',
        label: 'Glow',
        sectionPath: ['decoration', 'blur'],
        settings: [
          { key: 'enabled', label: 'Enable Glow', type: 'bool', desc: 'Enable glow effect' },
          { key: 'range', label: 'Glow Range', type: 'range', min: 0, max: 100, step: 1, unit: 'px', desc: 'Glow rendering distance' },
          { key: 'render_power', label: 'Glow Power', type: 'range', min: 1, max: 4, step: 1, unit: '', desc: 'Glow falloff sharpness' },
          { key: 'color', label: 'Glow Color', type: 'color', desc: 'Glow color' },
          { key: 'color_inactive', label: 'Inactive Glow Color', type: 'color', desc: 'Glow color for inactive windows' },
        ],
      },
    ],
  },
  {
    id: 'animations',
    label: 'Animations',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 12s2.545-5 7-5c4.454 0 7 5 7 5s-2.546 5-7 5c-4.455 0-7-5-7-5z"/><circle cx="12" cy="12" r="2"/><path d="m3 3 3 3m12 0 3-3M3 21l3-3m12 0 3 3"/></svg>`,
    group: 'APPEARANCE',
    subsections: [
      {
        id: 'animations_main',
        label: 'Animations',
        sectionPath: ['animations'],
        settings: [
          { key: 'enabled', label: 'Enable Animations', type: 'bool', desc: 'Master switch for all animations' },
          { key: 'workspace_wraparound', label: 'Workspace Wraparound', type: 'bool', desc: 'Animate workspace wraparound at the ends' },
        ],
        lists: [
          { key: 'bezier', label: 'Bezier Curves', desc: 'Define named bezier curves for animation timing' },
          { key: 'animation', label: 'Animation Rules', desc: 'Set animation name, style, speed and curve' },
        ],
      },
    ],
  },
  {
    id: 'layouts',
    label: 'Layouts',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="7" height="18" rx="1"/><rect x="14" y="3" width="7" height="11" rx="1"/><rect x="14" y="17" width="7" height="4" rx="1"/></svg>`,
    group: 'LAYOUTS',
    subsections: [
      {
        id: 'layout_misc',
        label: 'Layout Core',
        sectionPath: ['layout'],
        settings: [
          { key: 'single_window_aspect_ratio', label: 'Single Window Aspect Ratio', type: 'text', desc: 'Aspect ratio as "X Y" for single tiled windows' },
          { key: 'single_window_aspect_ratio_tolerance', label: 'Aspect Tolerance', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Tolerance before aspect correction is skipped' },
        ],
      },
      {
        id: 'dwindle',
        label: 'Dwindle Layout',
        sectionPath: ['dwindle'],
        settings: [
          { key: 'pseudotile', label: 'Pseudotile', type: 'bool', desc: 'Enable pseudotiling mode' },
          { key: 'preserve_split', label: 'Preserve Split', type: 'bool', desc: 'Keep split direction when a window is removed' },
          { key: 'smart_split', label: 'Smart Split', type: 'bool', desc: 'Always split in the wider dimension' },
          { key: 'smart_resizing', label: 'Smart Resizing', type: 'bool', desc: 'Resize neighbors proportionally' },
          { key: 'force_split', label: 'Force Split', type: 'select', options: ['0', '1', '2'], desc: '0=default, 1=left/top, 2=right/bottom' },
          { key: 'no_gaps_when_only', label: 'No Gaps When Only', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: '0=off, 1=no gaps, 2=no gaps and no border' },
          { key: 'use_active_for_splits', label: 'Use Active for Splits', type: 'bool', desc: 'Prefer active window as split target' },
          { key: 'default_split_ratio', label: 'Default Split Ratio', type: 'range', min: 0.1, max: 1.9, step: 0.05, unit: '', desc: '1.0 means 50/50' },
        ],
      },
      {
        id: 'master',
        label: 'Master Layout',
        sectionPath: ['master'],
        settings: [
          { key: 'allow_small_split', label: 'Allow Small Split', type: 'bool', desc: 'Allow splitting very small windows' },
          { key: 'special_scale_factor', label: 'Special Scale Factor', type: 'range', min: 0, max: 1, step: 0.01, unit: '', desc: 'Scale factor for the special workspace' },
          { key: 'mfact', label: 'Master Factor', type: 'range', min: 0.05, max: 0.95, step: 0.01, unit: '', desc: 'Master area size factor' },
          { key: 'new_is_master', label: 'New is Master', type: 'bool', desc: 'New window becomes master' },
          { key: 'new_on_top', label: 'New on Top', type: 'bool', desc: 'New windows appear at top of stack' },
          { key: 'no_gaps_when_only', label: 'No Gaps When Only', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: '0=off, 1=no gaps, 2=no gaps and no border' },
          { key: 'orientation', label: 'Orientation', type: 'select', options: ['left', 'right', 'top', 'bottom', 'center'], desc: 'Master window position' },
          { key: 'inherit_fullscreen', label: 'Inherit Fullscreen', type: 'bool', desc: 'Inherit fullscreen status' },
          { key: 'always_center_master', label: 'Always Center Master', type: 'bool', desc: 'Keep master window centered' },
          { key: 'smart_resizing', label: 'Smart Resizing', type: 'bool', desc: 'Resize neighbors proportionally' },
          { key: 'drop_at_cursor', label: 'Drop at Cursor', type: 'bool', desc: 'Drop slave at cursor position during drag' },
        ],
      },
      {
        id: 'group',
        label: 'Groups',
        sectionPath: ['group'],
        settings: [
          { key: 'insert_after_current', label: 'Insert After Current', type: 'bool', desc: 'Insert new group members after current window' },
          { key: 'focus_removed_window', label: 'Focus Removed Window', type: 'bool', desc: 'Refocus removed group window when detaching' },
          { key: 'drag_into_group', label: 'Drag Into Group', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: '0=disabled, 1=enabled, 2=invert logic' },
          { key: 'merge_groups_on_drag', label: 'Merge Groups on Drag', type: 'bool', desc: 'Merge groups when dragging grouped windows together' },
          { key: 'merge_floated_into_tiled_on_groupbar', label: 'Merge Floated Into Tiled', type: 'bool', desc: 'Allow floated windows to merge into tiled groups via groupbar' },
          { key: 'groupbar.enabled', label: 'Groupbar Enabled', type: 'bool', desc: 'Show a groupbar for grouped windows' },
          { key: 'groupbar.font_size', label: 'Groupbar Font Size', type: 'range', min: 6, max: 40, step: 1, unit: 'px', desc: 'Font size of groupbar title text' },
          { key: 'groupbar.gradients', label: 'Groupbar Gradients', type: 'bool', desc: 'Use gradient colors in groupbar' },
          { key: 'groupbar.height', label: 'Groupbar Height', type: 'range', min: 1, max: 80, step: 1, unit: 'px', desc: 'Height of the groupbar' },
          { key: 'groupbar.priority', label: 'Groupbar Priority', type: 'range', min: 0, max: 4, step: 1, unit: '', desc: 'Priority / placement mode for groupbar rendering' },
          { key: 'groupbar.render_titles', label: 'Render Titles', type: 'bool', desc: 'Render grouped window titles in the bar' },
          { key: 'groupbar.scrolling', label: 'Scrollable Groupbar', type: 'bool', desc: 'Allow scrolling the groupbar' },
          { key: 'groupbar.text_color', label: 'Groupbar Text Color', type: 'color', desc: 'Text color used by groupbar titles' },
          { key: 'groupbar.col.active', label: 'Groupbar Active Color', type: 'color', desc: 'Active group tab color' },
          { key: 'groupbar.col.inactive', label: 'Groupbar Inactive Color', type: 'color', desc: 'Inactive group tab color' },
          { key: 'groupbar.col.locked_active', label: 'Groupbar Locked Active', type: 'color', desc: 'Active color when group is locked' },
          { key: 'groupbar.col.locked_inactive', label: 'Groupbar Locked Inactive', type: 'color', desc: 'Inactive color when group is locked' },
        ],
      },
    ],
  },
  {
    id: 'input',
    label: 'Input',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="2" y="6" width="20" height="12" rx="2"/><path d="M6 10h.01M10 10h.01M14 10h.01M18 10h.01M6 14h12"/></svg>`,
    group: 'SYSTEM & DEVICES',
    subsections: [
      {
        id: 'keyboard',
        label: 'Keyboard',
        sectionPath: ['input'],
        settings: [
          { key: 'kb_layout', label: 'Layout', type: 'text', desc: 'Keyboard layout' },
          { key: 'kb_variant', label: 'Variant', type: 'text', desc: 'Keyboard layout variant' },
          { key: 'kb_model', label: 'Model', type: 'text', desc: 'Keyboard model' },
          { key: 'kb_options', label: 'Options', type: 'text', desc: 'XKB options' },
          { key: 'kb_rules', label: 'Rules', type: 'text', desc: 'XKB rules file' },
          { key: 'kb_file', label: 'XKB File', type: 'text', desc: 'Path to custom .xkb file' },
          { key: 'repeat_rate', label: 'Repeat Rate', type: 'range', min: 0, max: 100, step: 1, unit: '/s', desc: 'Key repeat rate' },
          { key: 'repeat_delay', label: 'Repeat Delay', type: 'range', min: 0, max: 3000, step: 10, unit: 'ms', desc: 'Delay before key repeat starts' },
          { key: 'numlock_by_default', label: 'Numlock Default', type: 'bool', desc: 'Enable Num Lock on startup' },
          { key: 'resolve_binds_by_sym', label: 'Resolve Binds by Sym', type: 'bool', desc: 'Resolve keybinds by symbol for active layout' },
          { key: 'special_fallthrough', label: 'Special Fallthrough', type: 'bool', desc: 'Allow focus fallthrough from special workspace' },
        ],
      },
      {
        id: 'mouse',
        label: 'Mouse',
        sectionPath: ['input'],
        settings: [
          { key: 'sensitivity', label: 'Sensitivity', type: 'range', min: -1, max: 1, step: 0.05, unit: '', desc: 'Mouse sensitivity' },
          { key: 'accel_profile', label: 'Accel Profile', type: 'select', options: ['adaptive', 'flat', 'custom'], desc: 'Pointer acceleration profile' },
          { key: 'force_no_accel', label: 'No Acceleration', type: 'bool', desc: 'Disable pointer acceleration completely' },
          { key: 'left_handed', label: 'Left Handed', type: 'bool', desc: 'Swap left and right buttons' },
          { key: 'follow_mouse', label: 'Follow Mouse', type: 'select', options: ['0', '1', '2', '3'], desc: '0=off, 1=loose, 2=strict, 3=loose+cursor lock' },
          { key: 'follow_mouse_threshold', label: 'Follow Threshold', type: 'range', min: 0, max: 100, step: 0.1, unit: 'px', desc: 'Minimum movement before hover-focus applies' },
          { key: 'mouse_refocus', label: 'Mouse Refocus', type: 'bool', desc: 'Refocus on mouse interaction' },
          { key: 'focus_on_close', label: 'Focus on Close', type: 'select', options: ['0', '1', '2'], desc: 'How focus is restored after closing a window' },
          { key: 'float_switch_override_focus', label: 'Float Override Focus', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: 'Focus override when switching float/tile' },
          { key: 'scroll_method', label: 'Scroll Method', type: 'select', options: ['no_scroll', '2fg', 'edge', 'on_button_down'], desc: 'Scroll method' },
          { key: 'scroll_button', label: 'Scroll Button', type: 'range', min: 0, max: 999, step: 1, unit: '', desc: 'Button used when scroll_method=on_button_down' },
          { key: 'scroll_button_lock', label: 'Scroll Button Lock', type: 'bool', desc: 'Lock scroll button direction' },
          { key: 'scroll_factor', label: 'Scroll Factor', type: 'range', min: 0, max: 5, step: 0.1, unit: 'x', desc: 'External mouse scroll multiplier' },
          { key: 'scroll_points', label: 'Scroll Points', type: 'text', desc: 'Custom accel points when accel_profile=custom' },
          { key: 'natural_scroll', label: 'Natural Scroll', type: 'bool', desc: 'Invert scroll direction' },
          { key: 'off_window_axis_events', label: 'Off-Window Axis Events', type: 'select', options: ['0', '1', '2', '3'], desc: 'How scroll events behave outside the focused window' },
          { key: 'emulate_discrete_scroll', label: 'Discrete Scroll Emu', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: 'Discrete scroll emulation mode' },
          { key: 'rotation', label: 'Rotation', type: 'range', min: 0, max: 359, step: 1, unit: 'deg', desc: 'Pointer device rotation' },
        ],
      },
      {
        id: 'touchpad',
        label: 'Touchpad',
        sectionPath: ['input', 'touchpad'],
        settings: [
          { key: 'natural_scroll', label: 'Natural Scroll', type: 'bool', desc: 'Invert scroll direction' },
          { key: 'disable_while_typing', label: 'Disable While Typing', type: 'bool', desc: 'Disable touchpad while typing' },
          { key: 'tap-to-click', label: 'Tap to Click', type: 'bool', desc: 'Enable tap-to-click' },
          { key: 'drag_lock', label: 'Drag Lock', type: 'select', options: ['0', '1', '2'], desc: '0=off, 1=timeout, 2=sticky' },
          { key: 'tap-and-drag', label: 'Tap and Drag', type: 'bool', desc: 'Enable tap-and-drag' },
          { key: 'tap_button_map', label: 'Tap Button Map', type: 'select', options: ['lrm', 'lmr'], desc: 'Finger tap button mapping' },
          { key: 'middle_button_emulation', label: 'Middle Button Emu', type: 'bool', desc: 'Emulate middle click with left+right press' },
          { key: 'clickfinger_behavior', label: 'Clickfinger Behavior', type: 'bool', desc: 'Use 1/2/3-finger physical clicks for L/R/M' },
          { key: 'scroll_factor', label: 'Scroll Factor', type: 'range', min: 0, max: 5, step: 0.1, unit: 'x', desc: 'Touchpad scroll multiplier' },
          { key: 'flip_x', label: 'Flip X', type: 'bool', desc: 'Invert horizontal touch movement' },
          { key: 'flip_y', label: 'Flip Y', type: 'bool', desc: 'Invert vertical touch movement' },
          { key: 'drag_3fg', label: 'Three-Finger Drag', type: 'select', options: ['0', '1', '2'], desc: '0=off, 1=3 fingers, 2=4 fingers' },
        ],
      },
      {
        id: 'gestures',
        label: 'Gestures',
        sectionPath: ['gestures'],
        settings: [
          { key: 'workspace_swipe_distance', label: 'Swipe Distance', type: 'range', min: 50, max: 1000, step: 10, unit: 'px', desc: 'Distance for a full workspace swipe' },
          { key: 'workspace_swipe_touch', label: 'Touchscreen Swipe', type: 'bool', desc: 'Enable workspace swipe from touchscreen edge' },
          { key: 'workspace_swipe_invert', label: 'Invert Swipe', type: 'bool', desc: 'Invert touchpad swipe direction' },
          { key: 'workspace_swipe_touch_invert', label: 'Invert Touch Swipe', type: 'bool', desc: 'Invert touchscreen swipe direction' },
          { key: 'workspace_swipe_min_speed_to_force', label: 'Min Swipe Speed', type: 'range', min: 0, max: 200, step: 1, unit: '', desc: 'Minimum speed to force workspace switch' },
          { key: 'workspace_swipe_cancel_ratio', label: 'Cancel Ratio', type: 'range', min: 0, max: 1, step: 0.05, unit: '', desc: 'Swipe cancel threshold ratio' },
          { key: 'workspace_swipe_create_new', label: 'Swipe Creates New', type: 'bool', desc: 'Create new workspace when swiping past the last' },
          { key: 'workspace_swipe_direction_lock', label: 'Direction Lock', type: 'bool', desc: 'Lock swipe direction once threshold is met' },
          { key: 'workspace_swipe_direction_lock_threshold', label: 'Direction Lock Threshold', type: 'range', min: 0, max: 100, step: 1, unit: 'px', desc: 'Distance before direction lock engages' },
          { key: 'workspace_swipe_forever', label: 'Swipe Forever', type: 'bool', desc: 'Allow continuous swiping past neighboring workspaces' },
          { key: 'workspace_swipe_use_r', label: 'Use R Workspaces', type: 'bool', desc: 'Swipe through r+N named workspaces' },
          { key: 'close_max_timeout', label: 'Close Max Timeout', type: 'range', min: 0, max: 5000, step: 50, unit: 'ms', desc: 'Timeout used by close gesture handling' },
        ],
        lists: [
          { key: 'gesture', label: 'Gesture Rules', desc: 'Gesture definition entries' },
        ],
      },
      {
        id: 'devices',
        label: 'Per-Device',
        sectionPath: [],
        settings: [],
        lists: [
          { key: 'device', label: 'Device Blocks', desc: 'Per-device overrides keyed by name / match' },
        ],
      },
      {
        id: 'touchdevice',
        label: 'Touch Devices',
        sectionPath: [],
        settings: [],
        lists: [
          { key: 'touchdevice', label: 'Touch Device Blocks', desc: 'Per-touch-device overrides' },
        ],
      },
      {
        id: 'tablet',
        label: 'Tablet',
        sectionPath: [],
        settings: [],
        lists: [
          { key: 'tablet', label: 'Tablet Blocks', desc: 'Tablet/tool configuration blocks' },
        ],
      },
      {
        id: 'virtual_keyboard',
        label: 'Virtual Keyboard',
        sectionPath: ['virtual_keyboard'],
        settings: [
          { key: 'enabled', label: 'Enabled', type: 'bool', desc: 'Enable virtual keyboard support' },
        ],
      },
    ],
  },
  {
    id: 'monitor',
    label: 'Monitor',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8m-4-4v4"/></svg>`,
    group: 'SYSTEM & DEVICES',
    subsections: [
      {
        id: 'monitor_list',
        label: 'Monitors',
        sectionPath: [],
        lists: [
          { key: 'monitor', label: 'Monitor Rules', desc: 'Monitor rules and monitorv2 entries' },
        ],
        settings: [],
      },
    ],
  },
  {
    id: 'xwayland',
    label: 'XWayland',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 4h7v7H4zM13 13h7v7h-7zM13 4h7v7h-7zM4 13h7v7H4z"/></svg>`,
    group: 'SYSTEM & DEVICES',
    subsections: [
      {
        id: 'xwayland_main',
        label: 'XWayland',
        sectionPath: ['xwayland'],
        settings: [
          { key: 'force_zero_scaling', label: 'Force Zero Scaling', type: 'bool', desc: 'Render XWayland at scale 1' },
          { key: 'use_nearest_neighbor', label: 'Nearest Neighbor', type: 'bool', desc: 'Use nearest-neighbor scaling for XWayland surfaces' },
          { key: 'create_abstract_socket', label: 'Abstract Socket', type: 'bool', desc: 'Create abstract XWayland socket' },
        ],
      },
    ],
  },
  {
    id: 'env',
    label: 'Env Variables',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16M4 12h16M4 18h16"/></svg>`,
    group: 'SYSTEM & DEVICES',
    subsections: [
      {
        id: 'env_list',
        label: 'Environment',
        sectionPath: [],
        lists: [
          { key: 'env', label: 'Environment Variables', desc: 'VAR,VALUE — environment variable for Hyprland and child processes' },
        ],
        settings: [],
      },
    ],
  },
  {
    id: 'misc',
    label: 'Miscellaneous',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="12" r="3"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14M4.93 4.93a10 10 0 0 0 0 14.14"/></svg>`,
    group: 'SYSTEM BEHAVIOR',
    subsections: [
      {
        id: 'misc_main',
        label: 'Miscellaneous',
        sectionPath: ['misc'],
        settings: [
          { key: 'disable_hyprland_logo', label: 'Disable Logo', type: 'bool', desc: 'Hide the default Hyprland logo/wallpaper' },
          { key: 'disable_splash_rendering', label: 'Disable Splash', type: 'bool', desc: 'Disable splash text on startup' },
          { key: 'disable_scale_notification', label: 'Disable Scale Notification', type: 'bool', desc: 'Hide scale fallback notification' },
          { key: 'col.splash', label: 'Splash Color', type: 'color', desc: 'Splash text color' },
          { key: 'font_family', label: 'Font Family', type: 'text', desc: 'Font for Hyprland UI text' },
          { key: 'splash_font_family', label: 'Splash Font', type: 'text', desc: 'Font for splash text' },
          { key: 'force_default_wallpaper', label: 'Force Default Wallpaper', type: 'range', min: -1, max: 2, step: 1, unit: '', desc: 'Wallpaper variant, -1 random/auto' },
          { key: 'vfr', label: 'VFR', type: 'bool', desc: 'Variable frame rate' },
          { key: 'vrr', label: 'VRR', type: 'select', options: ['0', '1', '2', '3'], desc: '0=off, 1=on, 2=fullscreen, 3=fullscreen game/video' },
          { key: 'mouse_move_enables_dpms', label: 'Mouse Enables DPMS', type: 'bool', desc: 'Wake displays on mouse movement' },
          { key: 'key_press_enables_dpms', label: 'Key Enables DPMS', type: 'bool', desc: 'Wake displays on key press' },
          { key: 'always_follow_on_dnd', label: 'Always Follow DnD', type: 'bool', desc: 'Follow cursor during drag-and-drop' },
          { key: 'layers_hog_keyboard_focus', label: 'Layers Hog Keyboard', type: 'bool', desc: 'Keyboard-interactive layers grab focus' },
          { key: 'animate_manual_resizes', label: 'Animate Manual Resize', type: 'bool', desc: 'Animate manual resize operations' },
          { key: 'animate_mouse_windowdragging', label: 'Animate Mouse Drag', type: 'bool', desc: 'Animate mouse window dragging' },
          { key: 'disable_autoreload', label: 'Disable Auto Reload', type: 'bool', desc: 'Disable automatic reload on config file change' },
          { key: 'enable_swallow', label: 'Enable Swallow', type: 'bool', desc: 'Swallow terminal when it launches a GUI app' },
          { key: 'swallow_regex', label: 'Swallow Regex', type: 'text', desc: 'Regex for windows eligible for swallowing' },
          { key: 'swallow_exception_regex', label: 'Swallow Exception Regex', type: 'text', desc: 'Regex for windows excluded from swallowing' },
          { key: 'focus_on_activate', label: 'Focus on Activate', type: 'bool', desc: 'Focus a window when it requests activation' },
          { key: 'mouse_move_focuses_monitor', label: 'Mouse Focuses Monitor', type: 'bool', desc: 'Moving mouse into monitor focuses it' },
          { key: 'allow_session_lock_restore', label: 'Restore on Lock', type: 'bool', desc: 'Allow lockscreen session restore after crash' },
          { key: 'initial_workspace_tracking', label: 'Initial Workspace Track', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: 'Initial workspace tracking mode' },
          { key: 'middle_click_paste', label: 'Middle Click Paste', type: 'bool', desc: 'Enable primary-selection paste' },
          { key: 'name_vk_after_proc', label: 'Name VK After Proc', type: 'bool', desc: 'Name virtual keyboards after creating process' },
          { key: 'session_lock_xray', label: 'Session Lock X-Ray', type: 'bool', desc: 'Keep rendering workspaces below lockscreen' },
          { key: 'background_color', label: 'Background Color', type: 'color', desc: 'Background color when default wallpaper is disabled' },
          { key: 'close_special_on_empty', label: 'Close Special on Empty', type: 'bool', desc: 'Close special workspace when last window leaves' },
          { key: 'on_focus_under_fullscreen', label: 'Focus Under Fullscreen', type: 'select', options: ['0', '1', '2'], desc: 'Behavior when another window activates under fullscreen' },
          { key: 'exit_window_retains_fullscreen', label: 'Retain Fullscreen on Close', type: 'bool', desc: 'Keep fullscreen after closing fullscreen window' },
          { key: 'render_unfocused_fps', label: 'Render Unfocused FPS', type: 'range', min: 1, max: 240, step: 1, unit: 'fps', desc: 'FPS cap for render_unfocused windows' },
          { key: 'disable_xdg_env_checks', label: 'Disable XDG Env Checks', type: 'bool', desc: 'Disable XDG environment warnings' },
          { key: 'disable_hyprland_qtutils_check', label: 'Disable hyprland-qtutils Check', type: 'bool', desc: 'Disable hyprland-qtutils warning' },
          { key: 'lockdead_screen_delay', label: 'Lockdead Delay', type: 'range', min: 0, max: 5000, step: 50, unit: 'ms', desc: 'Delay before lockdead screen appears' },
          { key: 'enable_anr_dialog', label: 'Enable ANR Dialog', type: 'bool', desc: 'Show application-not-responding dialog' },
          { key: 'anr_missed_pings', label: 'ANR Missed Pings', type: 'range', min: 1, max: 20, step: 1, unit: '', desc: 'Missed pings before ANR dialog' },
          { key: 'size_limits_tiled', label: 'Size Limits Tiled', type: 'bool', desc: 'Apply size limits to tiled windows' },
          { key: 'disable_watchdog_warning', label: 'Disable Watchdog Warning', type: 'bool', desc: 'Disable startup watchdog warning' },
        ],
      },
      {
        id: 'cursor_section',
        label: 'Cursor',
        sectionPath: ['cursor'],
        settings: [
          { key: 'invisible', label: 'Invisible Cursor', type: 'bool', desc: 'Do not render cursors' },
          { key: 'no_hardware_cursors', label: 'No HW Cursors', type: 'select', options: ['0', '1', '2'], desc: '0=use HW, 1=disable HW, 2=auto' },
          { key: 'no_break_fs_vrr', label: 'No Break FS VRR', type: 'select', options: ['0', '1', '2'], desc: 'Keep cursor updates from breaking fullscreen VRR' },
          { key: 'min_refresh_rate', label: 'Min Refresh Rate', type: 'range', min: 1, max: 240, step: 1, unit: 'Hz', desc: 'Minimum VRR refresh rate for cursor' },
          { key: 'hotspot_padding', label: 'Hotspot Padding', type: 'range', min: 0, max: 20, step: 1, unit: 'px', desc: 'Hotspot padding near edges' },
          { key: 'inactive_timeout', label: 'Inactive Timeout', type: 'range', min: 0, max: 60, step: 0.1, unit: 's', desc: 'Seconds before cursor hides' },
          { key: 'no_warps', label: 'No Warps', type: 'bool', desc: 'Disable cursor warping' },
          { key: 'persistent_warps', label: 'Persistent Warps', type: 'bool', desc: 'Restore relative cursor position on focus changes' },
          { key: 'warp_on_change_workspace', label: 'Warp on WS Change', type: 'select', options: ['0', '1', '2'], desc: 'Cursor warp behavior on workspace change' },
          { key: 'warp_on_toggle_special', label: 'Warp on Special Toggle', type: 'select', options: ['0', '1', '2'], desc: 'Cursor warp behavior on special workspace toggle' },
          { key: 'default_monitor', label: 'Default Monitor', type: 'text', desc: 'Monitor to warp cursor to' },
          { key: 'zoom_factor', label: 'Zoom Factor', type: 'range', min: 1, max: 10, step: 0.1, unit: 'x', desc: 'Cursor zoom magnification factor' },
          { key: 'zoom_rigid', label: 'Zoom Rigid', type: 'bool', desc: 'Rigid zoom without cursor offset' },
          { key: 'zoom_detached_camera', label: 'Detached Camera', type: 'bool', desc: 'Move zoom camera only near screen edges' },
          { key: 'enable_hyprcursor', label: 'HyprCursor', type: 'bool', desc: 'Enable HyprCursor support' },
          { key: 'sync_gsettings_theme', label: 'Sync GSettings Theme', type: 'bool', desc: 'Sync cursor theme with GSettings' },
          { key: 'hide_on_key_press', label: 'Hide on Key Press', type: 'bool', desc: 'Hide cursor after key press until moved' },
          { key: 'hide_on_touch', label: 'Hide on Touch', type: 'bool', desc: 'Hide cursor on touch input' },
          { key: 'hide_on_tablet', label: 'Hide on Tablet', type: 'bool', desc: 'Hide cursor on tablet input' },
          { key: 'use_cpu_buffer', label: 'Use CPU Buffer', type: 'select', options: ['0', '1', '2'], desc: 'Cursor compositing buffer mode' },
          { key: 'warp_back_after_non_mouse_input', label: 'Warp Back After Non-Mouse Input', type: 'bool', desc: 'Return cursor after non-mouse-driven motion' },
          { key: 'zoom_disable_aa', label: 'Zoom Disable AA', type: 'bool', desc: 'Disable antialiasing while zoomed' },
        ],
      },
      {
        id: 'render',
        label: 'Render',
        sectionPath: ['render'],
        settings: [
          { key: 'explicit_sync', label: 'Explicit Sync', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: 'Explicit sync mode' },
          { key: 'explicit_sync_kms', label: 'Explicit Sync KMS', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: 'Explicit sync KMS mode' },
          { key: 'direct_scanout', label: 'Direct Scanout', type: 'select', options: ['0', '1', '2'], desc: 'Direct scanout policy' },
          { key: 'expand_undersized_textures', label: 'Expand Undersized Textures', type: 'bool', desc: 'Expand undersized textures when needed' },
          { key: 'cm_fs_passthrough', label: 'Fullscreen Color Mgmt Passthrough', type: 'bool', desc: 'Allow fullscreen color-management passthrough' },
        ],
      },
      {
        id: 'opengl',
        label: 'OpenGL',
        sectionPath: ['opengl'],
        settings: [
          { key: 'nvidia_anti_flicker', label: 'NVIDIA Anti Flicker', type: 'bool', desc: 'Enable NVIDIA anti-flicker workaround' },
        ],
      },
      {
        id: 'ecosystem',
        label: 'Ecosystem',
        sectionPath: ['ecosystem'],
        settings: [
          { key: 'no_update_news', label: 'No Update News', type: 'bool', desc: 'Disable Hyprland update news messages' },
          { key: 'no_donation_nag', label: 'No Donation Nag', type: 'bool', desc: 'Disable donation reminder' },
          { key: 'enforce_permissions', label: 'Enforce Permissions', type: 'bool', desc: 'Enforce portal-style permission rules' },
        ],
      },
      {
        id: 'experimental',
        label: 'Experimental',
        sectionPath: ['experimental'],
        settings: [
          { key: 'xx_color_management_v4', label: 'Color Management v4', type: 'bool', desc: 'Enable experimental color-management protocol support' },
        ],
      },
      {
        id: 'debug',
        label: 'Debug',
        sectionPath: ['debug'],
        settings: [
          { key: 'overlay', label: 'Overlay', type: 'bool', desc: 'Enable debug overlay' },
          { key: 'damage_tracking', label: 'Damage Tracking', type: 'range', min: 0, max: 2, step: 1, unit: '', desc: 'Damage tracking mode' },
          { key: 'disable_logs', label: 'Disable Logs', type: 'bool', desc: 'Disable Hyprland logs' },
          { key: 'disable_time', label: 'Disable Time in Logs', type: 'bool', desc: 'Disable timestamps in logs' },
          { key: 'enable_stdout_logs', label: 'Stdout Logs', type: 'bool', desc: 'Mirror logs to stdout' },
          { key: 'colored_stdout_logs', label: 'Colored Stdout Logs', type: 'bool', desc: 'Colorize stdout logs' },
          { key: 'full_cm_proto', label: 'Full Color Mgmt Protocol', type: 'bool', desc: 'Enable full color-management debug protocol support' },
        ],
      },
      {
        id: 'misc_lists',
        label: 'Misc Lists',
        sectionPath: [],
        settings: [],
        lists: [
          { key: 'animation', label: 'Animation Rules', desc: 'Animation rule entries' },
          { key: 'bezier', label: 'Bezier Curves', desc: 'Bezier curve definitions' },
        ],
      },
    ],
  },
  {
    id: 'windowrules',
    label: 'Window Rules',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="18" height="18" rx="2"/><path d="M9 3v18M3 9h6m0 6H3"/></svg>`,
    group: 'LAYOUTS',
    subsections: [
      {
        id: 'windowrules_list',
        label: 'Window Rules',
        sectionPath: [],
        lists: [
          { key: 'windowrule', label: 'Window Rules', desc: 'Current syntax uses rule effects plus match:* filters' },
        ],
        settings: [],
      },
    ],
  },
  {
    id: 'layerrules',
    label: 'Layer Rules',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m12 2 10 6.5v7L12 22 2 15.5v-7L12 2z"/><path d="m12 22v-6.5M22 8.5l-10 7-10-7"/></svg>`,
    group: 'LAYOUTS',
    subsections: [
      {
        id: 'layerrules_list',
        label: 'Layer Rules',
        sectionPath: [],
        lists: [
          { key: 'layerrule', label: 'Layer Rules', desc: 'Current syntax uses effect rules with layer/namespace matching' },
        ],
        settings: [],
      },
    ],
  },
  {
    id: 'keybindings',
    label: 'Keybindings',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="2" y="7" width="20" height="13" rx="2"/><path d="M16 2v5m-8 0V2m4 0v5m-4 10H8m4-2v2m4 0h-4"/></svg>`,
    group: 'SYSTEM BEHAVIOR',
    subsections: [
      {
        id: 'binds_config',
        label: 'Bind Settings',
        sectionPath: ['binds'],
        settings: [
          { key: 'pass_mouse_when_bound', label: 'Pass Mouse When Bound', type: 'bool', desc: 'Pass mouse events through bound keys' },
          { key: 'scroll_event_delay', label: 'Scroll Event Delay', type: 'range', min: 0, max: 500, step: 10, unit: 'ms', desc: 'Delay between scroll events' },
          { key: 'workspace_back_and_forth', label: 'WS Back and Forth', type: 'bool', desc: 'Toggle last workspace on repeated switch' },
          { key: 'hide_special_on_workspace_change', label: 'Hide Special on WS Change', type: 'bool', desc: 'Hide special workspace on workspace change' },
          { key: 'allow_workspace_cycles', label: 'Allow WS Cycles', type: 'bool', desc: 'Allow cycling through workspaces' },
          { key: 'workspace_center_on', label: 'WS Center On', type: 'range', min: 0, max: 1, step: 1, unit: '', desc: '0=cursor, 1=previous window' },
          { key: 'focus_preferred_method', label: 'Focus Preferred Method', type: 'range', min: 0, max: 1, step: 1, unit: '', desc: '0=history, 1=shared edge length' },
          { key: 'ignore_group_lock', label: 'Ignore Group Lock', type: 'bool', desc: 'Dispatch group actions ignoring group lock' },
          { key: 'movefocus_cycles_fullscreen', label: 'MoveFocus Fullscreen', type: 'bool', desc: 'Move focus cycles through fullscreen windows' },
          { key: 'movefocus_cycles_groupfirst', label: 'MoveFocus Group First', type: 'bool', desc: 'Cycle inside groups before leaving them' },
          { key: 'window_direction_monitor_fallback', label: 'Directional Monitor Fallback', type: 'bool', desc: 'Fallback to adjacent monitor for directional dispatchers' },
          { key: 'disable_keybind_grabbing', label: 'Disable KB Grabbing', type: 'bool', desc: 'Disable keybind grabbing by apps' },
          { key: 'allow_pin_fullscreen', label: 'Allow Pin Fullscreen', type: 'bool', desc: 'Allow pinned windows to enter fullscreen' },
          { key: 'drag_threshold', label: 'Drag Threshold', type: 'range', min: 0, max: 100, step: 1, unit: 'px', desc: 'Distance before drag/click differentiation triggers' },
        ],
      },
      {
        id: 'keybindings_list',
        label: 'Key Bindings',
        sectionPath: [],
        lists: [
          { key: 'bind', label: 'Bindings', desc: 'bind = MODS, key, dispatcher, params' },
          { key: 'binde', label: 'Repeat Bindings', desc: 'Repeat while held' },
          { key: 'bindm', label: 'Mouse Bindings', desc: 'Mouse-driven binds' },
          { key: 'bindl', label: 'Locked Bindings', desc: 'Work while locked / inhibited' },
          { key: 'bindr', label: 'Release Bindings', desc: 'Fire on key release' },
          { key: 'bindc', label: 'Click Bindings', desc: 'Click-release bindings' },
          { key: 'bindg', label: 'Drag Bindings', desc: 'Release after drag-threshold bindings' },
          { key: 'bindd', label: 'Described Bindings', desc: 'Bindings with descriptions' },
          { key: 'bindk', label: 'Per-Device Bindings', desc: 'Bindings restricted to devices' },
          { key: 'unbind', label: 'Unbind', desc: 'Remove existing binds' },
          { key: 'submap', label: 'Submaps', desc: 'Named keybinding modes' },
        ],
        settings: [],
      },
    ],
  },
  {
    id: 'autostart',
    label: 'AutoStart',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 3l14 9-14 9V3z"/></svg>`,
    group: 'SYSTEM BEHAVIOR',
    subsections: [
      {
        id: 'autostart_list',
        label: 'Startup Commands',
        sectionPath: [],
        lists: [
          { key: 'exec-once', label: 'Exec Once', desc: 'Run once on Hyprland start' },
          { key: 'exec', label: 'Exec Always', desc: 'Run every time config is reloaded' },
        ],
        settings: [],
      },
    ],
  },
  {
    id: 'permissions',
    label: 'Permissions',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>`,
    group: 'SYSTEM BEHAVIOR',
    subsections: [
      {
        id: 'permission_list',
        label: 'Permissions',
        sectionPath: [],
        lists: [
          { key: 'permission', label: 'Permission Rules', desc: 'path,(screencast|plugin),allow|deny' },
        ],
        settings: [],
      },
    ],
  },
  {
    id: 'sources',
    label: 'Includes',
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="12" y1="18" x2="12" y2="12"/><line x1="9" y1="15" x2="15" y2="15"/></svg>`,
    group: 'UTILITY & DEBUGGING',
    subsections: [
      {
        id: 'sources_list',
        label: 'Sourced Files',
        sectionPath: [],
        lists: [
          { key: 'source', label: 'Source Directives', desc: 'Included config files' },
        ],
        settings: [],
      },
    ],
  },
];